#!/bin/bash

function Usage() {
    echo -e "Usage:\n\t$0 ip/id"
    echo "example: 
         $0 192.168.152.52
         $0 172023076058
    "
    exit 1
}

if [ $# -lt 1 ]; then
    Usage
fi

function check_ip() {
    IP=$1
    if [[ $IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        FIELD1=$(echo $IP|cut -d. -f1)
        FIELD2=$(echo $IP|cut -d. -f2)
        FIELD3=$(echo $IP|cut -d. -f3)
        FIELD4=$(echo $IP|cut -d. -f4)
        if [ $FIELD1 -le 255 -a $FIELD2 -le 255 -a $FIELD3 -le 255 -a $FIELD4 -le 255 ]; then
            echo "IP $IP available."
        else
            echo "IP $IP not available!"
            exit 1
        fi
    else
        echo "IP format error!"
        exit 2
    fi
}

function check_id() {
    echo $ID
    ID=$1
    if [[ $ID =~ ^[0-9]{12}$ ]]; then
        echo "ID $ID available."
        IP=$(awk '{for(i=0;i<4;i++)printf("%d%c",substr($0,i*3+1,3),i==3?"\n":".")}' <<< "$1")
        echo "IP: $IP"
    else
        echo "ID format error!"
        exit 2
    fi
}

function check() {
    if [[ $(expr index $1 .) -eq 0 ]];then
        check_id $1
    else
        check_ip $1
    fi 
}

check $1
echo $IP
ssh root@$IP
